# Generated by Django 5.1.6 on 2025-02-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
