# Generated by Django 5.1.6 on 2025-02-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSM', '0002_pedido_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
