# Generated by Django 5.1.6 on 2025-02-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSM', '0004_alter_burger_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
